### ISSUE TITLE
annoucment => announcement

### ISSUE THREAD

**Issue by cekk** [foxtrot-dfm1/announcement.engine#7]
**announcment** non esiste in inglese. Andrebbe cambiato ovunque in **announcement**.

Ti risparmio il nome del pacchetto a questo giro, perché poi sarebbe un po' un casino, ma il resto te lo faccio cambiare perché bisogna prestare più attenzione alle cose che si scrivono. Anche le singole label sono importanti e bisogna essere precisi nelle cose che si consegnano.

**Comment by foxtrot-dfm1** [comment]
Risolto: è stato fatto rebase al br. global_renaming dei tutti branch di sviluppo
